version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_DB: customerdb
      POSTGRES_PASSWORD: compose-postgres
  backend:
    image: cr-backend
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customerdb
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE=postgresql
  frontend:
    image: cr-frontend
    depends_on:
      - backend
    ports:
      - 4200:4200
